### ISSUE TITLE
ANDROID Only (New Arch): CameraRollModule is not abstract and does not override abstract method getPhotoThumbnail

### ISSUE THREAD

**Issue by isinuyk** [react-native-cameraroll/react-native-cameraroll#547]
Hi,

After upgrading from 5.9.0 to 5.10.0 it is not possible to build an Android app:

Task :react-native-camera-roll_camera-roll:compileDebugJavaWithJavac FAILED

```
node_modules\@react-native-camera-roll\camera-roll\android\src\main\java\com\reactnativecommunity\cameraroll\CameraRollModule.java:67: error: CameraRollModule is not abstract and does not override abstract method getPhotoThumbnail(String,ReadableMap,Promise) in NativeCameraRollModuleSpec
public class CameraRollModule extends NativeCameraRollModuleSpec {
       ^
Note: node_modules\@react-native-camera-roll\camera-roll\android\src\main\java\com\reactnativecommunity\cameraroll\CameraRollModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: node_modules\@react-native-camera-roll\camera-roll\android\src\main\java\com\reactnativecommunity\cameraroll\CameraRollPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-camera-roll_camera-roll:compileDebugJavaWithJavac'.
```

RN: 0.72.6
@react-native-cameraroll/react-native-cameraroll: 5.10.0+
New architecture enabled!

On IOS everything builds and works as expected.

**Comment by cetfu** [comment]
getting same error when enable the new architecture

**Comment by jp-23** [comment]
I'm looking into this.  I do notice that I only get this error when the new architecture is enabled.  If not enabled, I do not get the error.

**Comment by Arjan-Zuidema** [comment]
Should be fixed in [v6.0.2](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v6.0.2)

**Comment by khanhvohoangvib** [comment]
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/153273465/50dc3a0c-e741-45fa-afa3-d4f8fb993a0d)
I have this issue in v7.5.0 newArch enabled

**Comment by showtan001** [comment]
I have this issue in v7.5.0 newArch enabled. RN@0.73.6  @jp-23
