### ISSUE TITLE
import undefined.CameraRollPackage

### ISSUE THREAD

**Issue by raochenghui** [react-native-cameraroll/react-native-cameraroll#508]
import undefined.CameraRollPackage
When I finished all the manual configuration and started the project using the command, an error occurred。
> 
[1]xxx\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:17: ����: [1]�����undefined������
[1] import undefined.CameraRollPackage;
[1]                             ^
[1]xxx\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:80: ����: �Ҳ�������
[1]       new CameraRollPackage(),
[1]           ^
[1]   ����:   �� CameraRollPackage
[1]   λ��: �� PackageList
[1] ע: xxx\android\app\src\debug\java\com\appframe\ReactNativeFlipper.javaʹ�û򸲸����ѹ�ʱ�� API��
[1] ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
[1] 2 ������
[1]
[1] FAILURE: Build failed with an exception.
[1]
[1] * What went wrong:
[1] Execution failed for task ':app:compileDebugJavaWithJavac'.
[1] > Compilation failed; see the compiler error output for details.
[1]
[1] * Try:
[1] > Run with --stacktrace option to get the stack trace.
[1] > Run with --info or --debug option to get more log output.
[1] > Run with --scan to get full insights.
[1]
[1] * Get more help at https://help.gradle.org
[1]
[1] BUILD FAILED in 59s
[1]
[1]     at makeError (xxx\node_modules\execa\index.js:174:9)
[1]     at xxx\node_modules\execa\index.js:278:16
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async runOnAllDevices (xxx\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5) 
[1]     at async Command.handleAction (xxx\node_modules\@react-native-community\cli\build\index.js:192:9)
[1] info Run CLI with --verbose flag for more details.

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/00d335c2-3c3e-4a40-9158-c86380f33ee1)

Manually install according to documentation.
react-native: "0.68.2"
"@react-native-camera-roll/camera-roll": "^5.7.1",
in MainApplication.java
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/72572d87-7313-4f36-a3a0-9ff5af9fb8a5)
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/a1938a70-1475-48f2-8342-55e6d30e183e)
in android/app/build.gradle
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/6bf5cdc7-f656-439c-98e4-60e28810258b)
in android/settings.gradle
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/4d6160ed-5600-4cc2-a83f-678e83ac47e7)

**Comment by Arjan-Zuidema** [comment]
Can you remove the build directory and try again? The error does not seem to occur on my end.

You can also try this command:
`$ cd android && ./gradlew clean`

**Comment by raochenghui** [comment]
> 
Thank you for your reply，I've already tried，but it still is undefined

**Comment by Arjan-Zuidema** [comment]
Can you try `$ npm install @react-native-camera-roll/camera-roll@5.6` and see if it also occurs on and older version

**Comment by raochenghui** [comment]
> @react-native-camera-roll/camera-roll@5.6

I switched to 5.6.0 and it didn't have this problem

**Comment by raochenghui** [comment]
> occurs

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/40efaaae-477d-4294-8e41-4e384748333f)
Because of this problem, I have modified the following part of the code, I do not know whether it has any impact。
in android/app/build.gradle
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/e58f723e-0a0b-441f-a080-42ebdd7a70f2)
in andriod/build.gradle
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70825629/2d91f62c-b96e-4d23-a147-6e2091a34362)

**Comment by Arjan-Zuidema** [comment]
What version of react-native are you using? I see 0.68.2 in your Gradle file and 0.71.0-RC.0 in the build log.

**Comment by raochenghui** [comment]
> What version of react-native are you using? I see 0.68.2 in your Gradle file and 0.71.0-RC.0 in the build log.
I used 0.68.2, but I don't know why 0.71.0-RC appears in the log when I start the project. I looked it up and said it was a react-native bug

**Comment by Arjan-Zuidema** [comment]
I suggest you stay on 5.6.1 as 5.7.1 only adds support for react-native 0.73. If this problem occurs on react-native 0.73 we can reopen this and investigate further.

**Comment by markrickert** [comment]
I was having this problem as well (currently on react native 0.68.7) and downgrading this library to 5.7.1 fixed my build-time issues.

**Comment by RandomToni** [comment]
Hello, me too. Only happens when compiling for release, but not for debug build.

**Comment by Arjan-Zuidema** [comment]
I just tested this on my local machine in release build and still can't reproduce the error. What version of react-native are you using @RandomToni

**Comment by RandomToni** [comment]
hi, I can confirm it's working with rn 0.68.7 and the lib version 5.6.1. Thank you.

**Comment by mehmetsalihyaldiz** [comment]
Hello, i had a problem. React Native version: 0.66.4 and React: 17.0.2

**Comment by basilkurianmb** [comment]
@raochenghui 

Did you able to resolve this issue? I'm also facing the same issue since last 2 weeks. I'm sure that this same code was working prior to 2 weeks before.

I'm working with react native 0.67.5 and "@react-native-camera-roll/camera-roll": "^5.4.0". 

I tired multiple ways but this issue is still coming.

```
/<path>/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: error: package undefined does not exist
import undefined.CameraRollPackage;

/<path>/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:108: error: cannot find symbol
      new CameraRollPackage(),
          ^
  symbol:   class CameraRollPackage
```

**Comment by raochenghui** [comment]
@basilkurianmb 
@react-native-camera-roll/camera-roll": "^5.4.0", you must delete the '^'. I suggest you stay on 5.6.1 or use lower version

**Comment by basilkurianmb** [comment]
@raochenghui 

Thank you so much 

It worked!!!

**Comment by coderYes** [comment]
> @raochenghui
> 
> Thank you so much
> 
> It worked!!!

+1

**Comment by mehmetsalihyaldiz** [comment]
> Hello, i had a problem. React Native version: 0.66.4 and React: 17.0.2

We are now in the latest version. 🤷‍♂️

**Comment by Noitham** [comment]
Why was this marked as closed?

The issue does occur when using `"@react-native-camera-roll/camera-roll": "5.7.2"`, on for example, a project using `react-native@0.67.5`.

**Comment by raochenghui** [comment]
> Why was this marked as closed?
> 
> The issue does occur when using `"@react-native-camera-roll/camera-roll": "5.7.2"`, on for example, a project using `react-native@0.67.5`.

You can look at all the replies and try to use a lower version, such as 5.6.0

**Comment by Noitham** [comment]
> 

Yeah, for now a temporary solution, but we might want to update the package version in the future :thinking:
