### ISSUE TITLE
Fix for error: unreported exception IOException; must be caught or declared to be thrown       retriever.release()

### ISSUE THREAD

**Issue by spinoza1791** [react-native-cameraroll/react-native-cameraroll#429]
Prereq 
 "dependencies": {
    "@react-native-community/cameraroll": "^4.1.2",

When upgrading app/build.gradle version to 7.2.2
...
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.2")

Then, npx react-native run-android
BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\Projects\psp - splash4 - 8-29\node_modules\@react-native-community\cameraroll\android\src\main\java\com\reactnativecommunity\cameraroll\CameraRollModule.java:650: error: unreported exception IOException; must be caught or declared to be thrown
      retriever.release();

Solution:
Modify CameraRollModule.java by replacing bare "retriever.release();" (in two areas of this java file, with a caught version -

          try {
            retriever.release();
          } catch (IOException e) {
            // Do nothing. We can't handle this, and this is usually a system problem
          }

This allows the upgrade of app/build.gradle version to 7.2.2
...
classpath("com.android.tools.build:gradle:7.2.2")

**Comment by Arjan-Zuidema** [comment]
Please upgrade to the latest version. It has been fixed in [5.0.2](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v5.0.2)
